### ISSUE TITLE
Unable to install zerotier; Unable to install dependencies

### ISSUE THREAD

**Issue by BlipRanger** [YunoHost-Apps/zerotier_ynh#32]
### Describe the bug

A failure to install due to not being able to locate / install dependencies. 

### Context

- Hardware: OrangePi Zero
- YunoHost version: 11.1.7
- I have access to my server: SSH/Webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Yes
  - If yes, please explain: Installed TOR for (current) remote access. 
- Using, or trying to install package version/branch: 1.10.2~ynh1
- If upgrading, current package version: n/a

### Steps to reproduce

`sudo yunohost app install https://github.com/YunoHost-Apps/zerotier_ynh/`

### Expected behavior

The app installs completely. 

### Logs

https://paste.yunohost.org/raw/wahuvusaye

**Comment by CMDren** [comment]
Same here :/

**Comment by Salamandar** [comment]
Hi, it should be fixed :)
